### PR TITLE
Added CUDA support

### PR DESCRIPTION
**Pull request by jfsantos**
First, thanks for sharing this! I was going to implement the MDN criterion on Torch yesterday, but then found you had done it already.

This PR adds CUDA support to your code. The only difference is that it ships all the needed variables to the GPU. I also added a small value to the sum of the probabilities just in case (I got some `nans` for the cost while running the code earlier today, but that fix alone apparently wasn't enough).

### CODE REVIEW

**Comment by johnglover** [comment]
This is great, thanks!

**Comment by johnglover** [comment]
Forgot to ask, what was the reason for switching to rmsprop here?

**Comment by jfsantos** [comment]
Sorry, that's something I forgot to remove from my tests. There's no technical reason, I was just playing with different algorithms and observing the training error curves.

**Comment by johnglover** [comment]
Cool, was just wondering if you had better results with whatever audio you were using with rmsprop (I tried both but adagrad seemed to work better in my relatively short training times).

**Pull request merged**
